[phases.setup]
nixPkgs = ['nodejs_20', 'bun']
aptPkgs = ['curl', 'wget']
nixOverlays = ['https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz']
nixpkgsArchive = 'ffeebf0acf3ae8b29f8c7049cd911b9636efd7e7'

[phases.install]
dependsOn = ['setup']
cmds = ['bun install']
cacheDirectories = ['/root/.bun']
paths = ['/app/node_modules/.bin']

[phases.build]
dependsOn = ['install']
cmds = ['npx turbo run build']
cacheDirectories = ['apps/mail/.next/cache', 'node_modules/.cache']

[start]
cmd = 'bun docker up'

[variables]
CI = 'true'
NIXPACKS_METADATA = 'node'
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'
